# Generated by Django 4.0.2 on 2022-02-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_paicipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='paicipants',
            new_name='participants',
        ),
    ]
